name: Hello Actions!

on:
  push:
    branches:
      -master

jobs:
  hello_actions_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello fromm Github Actions!"