name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  pipeline:
    name: Lint, Test n Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: set environment
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "PR_COMMIT_MESSAGE=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/jaakkohurtta/general-testing-repo/commits/${SHA} \
          | jq '.commit.message')" >> $GITHUB_ENV
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to heroky
        if: ${{ github.event_name == 'push' && !contains(env.PR_COMMIT_MESSAGE, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "agile-thicket-54021"
          heroku_email: jaakko.hurtta@outlook.com
          healthcheck: "https://agile-thicket-54021.herokuapp.com/health"
          delay: 1
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(env.PR_COMMIT_MESSAGE, '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.11.0
